New features
------------

* align_abs() comes now with two aligment methods. The sidewalk alignment has been added to default bysorting
  method (see the :ref:`processes section <processes>` for details).

* added a feature (see the :ref:`miscellaneous section <misc>` for details).

* added another feature.

.. _misc:

Miscellaneous improvements
--------------------------

* improved something.

Fixes
-----

* fixed something (closes :issue:`1`).
