New features
------------

* chart functions gained *xmin*, *xmax*, *ymin*, *ymax* optional arguments to
  provide manual bounds for axes. By default, they are automatically inferred
  from the data (closes :issue:`209`).

Miscellaneous improvements
--------------------------

* view command can be called without file argument to launch the embedded
  ViTables without opening any file (closes :issue:`194`).