New features
------------

* added a feature (see the :ref:`miscellaneous section <misc>` for details).

* added another feature.

.. _misc:

Miscellaneous improvements
--------------------------

* improved something.

Fixes
-----

* Fix parsing error of function when their name termination is ìf (closes :issue:`280`)

* Fix error message when checking fields definitions (:pr:`133`).

* Allow to import import files from within import files as in simulation console files (closes :issue:`302`).

* Allow the use of while as a keyword and a function to avoid silent mistakes (closes :issue:`314`).

* fixed duration() function when no output file is specified (fixes #300).
