New features
------------

* A default value can be assigned to fields that are not present
 in the initial data (see the :ref:`miscellaneous section <model>` for details).

* added a feature (see the :ref:`model section <misc>` for details).

* added another feature.

.. _misc:

Miscellaneous improvements
--------------------------

* improved something.

Fixes
-----

* fixed something (closes :issue:`1`).
