New features
------------

* added a feature (see the :ref:`miscellaneous section <misc>` for details).

* chart functions gained *xmin*, *xmax*, *ymin*, *ymax* optional arguments to
  provide manual bounds for axes. By default, they are automatically inferred
  from the data (closes :issue:`209`).

.. _misc:

Miscellaneous improvements
--------------------------

* improved something.

Fixes
-----

* fixed something (closes :issue:`1`).
