New features

------------

* added the rank_matching() function as an other method to match two sets of 
individuals.

* add the possibility to generate automatically an order in matching. The two
possible new options are 'EDtM' and 'SDtOM'.

* add an new 'pool_size' optional parameter in matching. If an integer is
entered the best match for an individual is looked for in a random subset
of size pool_size.

--------------------------

Fixes

-----